version: '3'

services:
  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    network_mode: host
    environment:
      - PLEX_CLAIM=your_plex_claim_token
      - ADVERTISE_IP=http://your_server_ip:32400/
      - PLEX_UID=1000  # Change to your UID
      - PLEX_GID=1000  # Change to your GID
    volumes:
      – /docker/plex/config:/config
      – /docker/plex/transcodes:/transcode
      – /docker/plex/filme:/docker/plex/filme
      - /docker/plex/serien:/docker/plex/serien
      – /docker/plex/musik:/docker/plex/musik
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    restart: unless-stopped

