---
version: "2.1"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - /docker/plex/config:/config
      - /docker/plex/transcode:/transcode
      - /docker/plex/filme:/films
      - /docker/plex/serien:/series
      - /docker/plex/musik:/music
    restart: unless-stopped