version: 3.7
services:

  plex:
    image: plexinc/pms-docker
    restart: unless-stopped
    container_name: plexms
    ports:
      – “32400:32400/tcp”
      – “3005:3005/tcp”
      – “8324:8324/tcp”
      – “32469:32469/tcp”
      – “1900:1900/udp”
      – “32410:32410/udp”
      – “32412:32412/udp”
      – “32413:32413/udp”
      – “32414:32414/udp”

    environment:
      – PUID=1000
      – PGID=1000
      – TZ=Europe/Berlin
      – PLEX_CLAIM=claim-x7oVwakS1ybDRxw8CdPD
      – HOSTNAME=”PlexServer”

    volumes:
      – /docker/plex/config:/config
      – /docker/plex/transcodes:/transcode
      – /docker/plex/filme:/docker/plex/filme
      - /docker/plex/serien:/docker/plex/serien
      – /docker/plex/musik:/docker/plex/musik